version: 0.2

# AWS CodeBuild specification for Spring Boot Notes Backend
# This file defines the build process for CI/CD pipeline

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies..."
      - echo "Java version:"
      - java -version
      
  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - echo "Changing to notes-backend directory..."
      - cd notes-backend
      - echo "Making mvnw executable..."
      - chmod +x ./mvnw
      - echo "Skipping tests for faster CI/CD deployment..."
      
  build:
    commands:
      - echo "Build phase started on `date`"
      - echo "Building JAR file..."
      - ./mvnw clean package -DskipTests
      - echo "Build completed on `date`"
      
  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      - echo "Preparing deployment artifacts..."
      - mv target/*.jar application.jar
      - ls -la
      
artifacts:
  files:
    - application.jar
    - .ebextensions/**/*
    - Procfile
  name: notes-backend-$(date +%Y%m%d-%H%M%S).zip
  discard-paths: no
  base-directory: notes-backend
  
cache:
  paths:
    - '/root/.m2/**/*'
