version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  notes-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/notes
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: manage
    depends_on:
      - postgres

volumes:
  postgres_data:
